[project]
name = "nishikihebi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kaíque Kandy Koga", email = "kaiquekandykoga@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
nishikihebi = "nishikihebi:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.16.1",
]
